package parser

import "testing"

func TestClassifyUserTextHarnessWrappers(t *testing.T) {
	cases := []struct {
		text    string
		want    MessageKind
		harness bool
	}{
		{"<command-name>/model</command-name>", KindCommand, true},
		{"<local-command-stdout>Set model to Haiku</local-command-stdout>", KindCommandOutput, true},
		{"<local-command-stderr>error</local-command-stderr>", KindCommandOutput, true},
		{"<local-command-caveat>Caveat: generated by local commands</local-command-caveat>", KindCommandOutput, true},
		{"<task-notification>\n<task-id>abc</task-id>", KindNotification, true},
		{"  <task-notification>leading whitespace", KindNotification, true},
		{"[Request interrupted by user]", KindInterrupt, true},
		{"[Request interrupted by user for tool use]", KindInterrupt, true},
		{"fix the login bug", KindUnknown, false},
		{"", KindUnknown, false},
	}
	for _, c := range cases {
		got, harness := ClassifyUserText(c.text)
		if harness != c.harness || (harness && got != c.want) {
			t.Errorf("ClassifyUserText(%q) = (%v, %v), want (%v, %v)", c.text, got, harness, c.want, c.harness)
		}
	}
}

func TestClassifyMessageHarnessWrappersNotUserPrompt(t *testing.T) {
	// Content-block path
	msg := &Message{
		Type:    "user",
		Content: []ContentBlock{{Type: "text", Text: "<local-command-stdout>ok</local-command-stdout>"}},
	}
	if got := classifyMessage(msg, rawMessage{}); got != KindCommandOutput {
		t.Errorf("command output classified as %v, want %v", got, KindCommandOutput)
	}

	// Raw-string content path
	msg2 := &Message{Type: "user"}
	raw2 := rawMessage{Message: messagePayload{Content: "<task-notification>done</task-notification>"}}
	if got := classifyMessage(msg2, raw2); got != KindNotification {
		t.Errorf("task notification classified as %v, want %v", got, KindNotification)
	}

	// Command still detected and annotated
	msg3 := &Message{
		Type:    "user",
		Content: []ContentBlock{{Type: "text", Text: "<command-name>/compact</command-name>"}},
	}
	if got := classifyMessage(msg3, rawMessage{}); got != KindCommand {
		t.Errorf("command classified as %v, want %v", got, KindCommand)
	}
	if !msg3.IsCommand || msg3.CommandName != "/compact" {
		t.Errorf("command annotation lost: IsCommand=%v name=%q", msg3.IsCommand, msg3.CommandName)
	}
}

func TestComputeStatsExcludesHarnessTurns(t *testing.T) {
	msgs := []*Message{
		{Type: "user", Kind: KindUserPrompt},
		{Type: "user", Kind: KindCommandOutput},
		{Type: "user", Kind: KindNotification},
		{Type: "user", Kind: KindCommand},
		{Type: "assistant", Kind: KindAssistant},
	}
	stats := computeStats(msgs)
	if stats.UserPrompts != 1 {
		t.Errorf("UserPrompts = %d, want 1", stats.UserPrompts)
	}
}

func TestIsToolDenial(t *testing.T) {
	yes := []string{
		"The user doesn't want to proceed with this tool use. The tool use was rejected (eg. if it was a file edit, the new_string was NOT written to the file).",
		"  The user doesn't want to take this action right now. STOP what you are doing",
	}
	no := []string{"Exit code 137\n[Request interrupted by user for tool use]", "permission denied: /etc/shadow", ""}
	for _, s := range yes {
		if !IsToolDenial(s) {
			t.Errorf("IsToolDenial(%q) = false, want true", s)
		}
	}
	for _, s := range no {
		if IsToolDenial(s) {
			t.Errorf("IsToolDenial(%q) = true, want false", s)
		}
	}
}
